### ISSUE TITLE
Error when moving past multi byte characters

### ISSUE THREAD

**Issue by lervag** [machakann/vim-columnmove#1]
I was made aware of this plugin due to [this](https://vi.stackexchange.com/questions/3929/column-wise-f-f-t-t) question on vi.stackexchage.com. It seems like a very nice plugin!

When testing it, I noticed that the columnwise motions are wrong when there are multi byte characters (or something similar). That is:

```
aa|a
aaa

bbb
øbb

ccc
ccc
```

Let `|` denote where the cursor is (i.e. first line column two). Now do `<m-w>` twice. This should leave the cursor on the second column on the sixth line, but instead I end up at the first column. The reason is that `ø` is a multi byte character or something like that.

**Comment by machakann** [comment]
Great! Your advice is quite correct, that is the best way to map keys in operator-pending mode. I also do this kind of "column-wise cut" frequently.

I take a glance at the source code. Since the process for the lines containing multibyte characters is heavy in general way, I put several short-cut conditions for simple cases to make faster. But one of them has been failed. Now it has fixed (4b218642fc43a097ea971f691daeb0a43cdd0b8d), please check.

**Comment by lervag** [comment]
Thanks, it is fixed now!
