### ISSUE TITLE
Suggestion for options: block-wise operator mode option

### ISSUE THREAD

**Issue by lervag** [machakann/vim-columnmove#2]
As I suggested in a comment [here](https://vi.stackexchange.com/questions/3929/column-wise-f-f-t-t), I think it makes sense to map the operator mode for columnmove directly to the block wise modes, in order to be able to do deletes and replaces along the columns.

It is very simple to do this with custom mappings, as I've done (see [here](https://github.com/lervag/dotvim/commit/855f5d0549b8d1edcf2f3451b8c10554293f0596#diff-076d61938d25fd036d6436c94d8778faR212)). However, I think this feature could be added as an optional feature.

**Comment by machakann** [comment]
It is not as an option, but I added a new utility function `call columnmove#utility#map()`. This function help user to define keymappings, and the fourth argument `motionwise` is the key, it can determine the default motionwise in operator-pending mode. For example:

``` vim
let g:columnmove_no_default_key_mappings = 1
call columnmove#utility#map('nxo', 'f', '\f', 'block')
" press d\fh
" a#c        ac
" def   ->   df     #:cursor
" ghi        g#

" The above descriptions are identical to the following lines.
" let g:columnmove_no_default_key_mappings = 1
" nnoremap <silent><expr>      \f columnmove#f('n', '')
" xnoremap <silent><expr>      \f columnmove#f('x', '')
" onoremap <silent><expr> <C-v>\f columnmove#f('o', "<Bslash><lt>C-v>")
" onoremap <silent><expr>     v\f columnmove#f('o', '')
" onoremap <silent><expr>     V\f columnmove#f('o', 'V')
" onoremap <silent><expr> <C-v>\f columnmove#f('o', "<Bslash><lt>C-v>")
```

Sorry, it might not be exactly same as you expected, but I think the function solves several problems of this plugin. Actually I was not so serious about this plugin when I started to write. However after using for a while, I found that this is somewhat useful. Now I regret that I map them to <M-*> as default, because it is not valid in terminal emulator environments. I think this function also can allow to remap them easily. Could the function be the answer for this issue?

**Comment by lervag** [comment]
So, to create all mappings, I could do:

``` vimL
for x in split('ftFT;,wbeWBE', '\zs') + ['ge', 'gE']
  call columnmove#utility#map('nxo', x, '\' . x, 'block')
endfor
```

This seems to work, and it seems a like an OK way to solve my issue. That is, instead of 42 lines, I can now settle with 3 lines to create all maps.

Note, I think there is a typo in your reply. The first `onoremap` should be only

``` vimL
" onoremap <silent><expr>      \f columnmove#f('o', "<Bslash><lt>C-v>")
```

**Comment by lervag** [comment]
By the way: Here it seems your preference have changed from using the meta (or alt) key to using a leader-like prefix. Is this your current preferance, and is this something you personally recommend?

**Comment by machakann** [comment]
Umm... Just personally I'm using alt key mapping, but to be honest I recommend to use <leader> prefix. Because alt key is not valid in cui though I mainly use gvim.exe.

About the example, you are right. It is a typo, sorry!

**Comment by lervag** [comment]
Ok, thanks for your input.
